CREATE TABLE company
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name   VARCHAR(255)                            NOT NULL,
    budget BIGINT                                  NOT NULL,
    CONSTRAINT pk_company PRIMARY KEY (id)
);

ALTER TABLE company
    ADD CONSTRAINT uc_company_name UNIQUE (name);

CREATE TABLE company_employee
(
    company_id BIGINT NOT NULL,
    user_id    BIGINT NOT NULL
);

ALTER TABLE company_employee
    ADD CONSTRAINT FK_COMPANY_EMPLOYEE_ON_COMPANY FOREIGN KEY (company_id) REFERENCES company (id);