server:
  port: 8082

spring:
  application:
    name: company
#  config:
#    import: optional:configserver:${CONFIG_URL:http://localhost:8888/}
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:company
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761/eureka}
